import { useNavigate } from 'react-router-dom'
import { useTheme } from '../lib/useTheme'
import Switch from '../components/Switch'
import './Legal.css'

function Terms() {
  const navigate = useNavigate()
  const [theme, toggleTheme] = useTheme()

  return (
    <div className="legal-page">
      <nav className="nav legal-nav">
        <button className="back-btn" onClick={() => navigate(-1)}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="15 18 9 12 15 6"/>
          </svg>
          Back
        </button>
        <span className="nav-logo" onClick={() => navigate('/')} style={{ cursor: 'pointer' }}>
          &#x1F33F; Poshanix
        </span>
        <Switch checked={theme === 'dark'} onToggle={toggleTheme} />
      </nav>

      <main className="legal-main">
        <div className="legal-header">
          <span className="legal-tag">Legal</span>
          <h1>Terms of Service</h1>
          <p className="legal-date">Last updated: February 21, 2026</p>
        </div>

        <div className="legal-body">
          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>By accessing or using Poshanix, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, please do not use the service.</p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>Poshanix is an AI-powered nutrition analysis platform that allows users to scan food items and receive nutritional information. The service is provided "as is" and is intended for informational purposes only.</p>
          </section>

          <section>
            <h2>3. User Accounts</h2>
            <p>You are responsible for:</p>
            <ul>
              <li>Maintaining the confidentiality of your account credentials.</li>
              <li>All activities that occur under your account.</li>
              <li>Notifying us immediately of any unauthorised use of your account.</li>
            </ul>
          </section>

          <section>
            <h2>4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the service for any unlawful purpose.</li>
              <li>Attempt to reverse-engineer any part of the platform.</li>
              <li>Upload content that is harmful, offensive, or violates any third-party rights.</li>
              <li>Use automated tools to scrape or abuse the service.</li>
            </ul>
          </section>

          <section>
            <h2>5. Nutritional Information Disclaimer</h2>
            <p>Nutritional data and analysis provided by Poshanix is generated by AI and is for informational purposes only. It should not be used as a substitute for professional dietary or medical advice. Always consult a qualified professional for health-related decisions.</p>
          </section>

          <section>
            <h2>6. Intellectual Property</h2>
            <p>All content, branding, and technology within Poshanix is the property of Poshanix and its licensors. You may not copy, reproduce, or distribute any part of the service without prior written permission.</p>
          </section>

          <section>
            <h2>7. Termination</h2>
            <p>We reserve the right to suspend or terminate your account at any time for violations of these terms or for any other reason at our sole discretion.</p>
          </section>

          <section>
            <h2>8. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Poshanix shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
          </section>

          <section>
            <h2>9. Changes to Terms</h2>
            <p>We may update these Terms of Service from time to time. Continued use of the service after changes constitutes acceptance of the revised terms.</p>
          </section>

          <section>
            <h2>10. Contact</h2>
            <p>For questions about these terms, contact us at <a href="mailto:noreply.poshanix@gmail.com">noreply.poshanix@gmail.com</a>.</p>
          </section>
        </div>
      </main>

      <footer className="footer legal-footer">
        &copy; {new Date().getFullYear()} Poshanix &mdash;{' '}
        <span className="legal-footer-link" onClick={() => navigate('/privacy')}>Privacy Policy</span>
      </footer>
    </div>
  )
}

export default Terms
